version: 0.0
os: linux
    destination: /data/awsdemoapp/web
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 3600
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 3600
