version: 0.0
os: linux
files:
  - source: /index.html
    destination: /data/awsdemoapp/web
hooks:
  StopApplication:
    - location: scripts/beforeinstall.sh
      timeout: 3600
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 3600
